"""Rasterize DSEG7 Classic Bold into a BitmapFont header for P-OBC.

Usage: python gen.py
Output: include/Fonts_DSEG7.h

Chars: 0-9 : . - /
Sizes: 96 and 48 px digit-height (target).
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FONT_FILE = "DSEG7Classic-Bold.ttf"
FONT_NAME = "DSEG7"
CHARS = "0123456789:.-/"
TARGETS = [120, 60]  # desired digit-cap height in pixels
OUT_HEADER = Path(f"../../include/Fonts_{FONT_NAME}.h")
OUT_SOURCE = Path(f"../../src/Fonts_{FONT_NAME}.cpp")


def measure_digit_height(font):
    img = Image.new("L", (font.size * 3, font.size * 3), 0)
    d = ImageDraw.Draw(img)
    d.text((font.size, font.size), "8", font=font, fill=255)
    bbox = img.getbbox()
    return bbox[3] - bbox[1] if bbox else 0


def pick_size_for_digit_height(font_path, target_h):
    lo, hi = 8, target_h * 3
    best = lo
    while lo <= hi:
        mid = (lo + hi) // 2
        f = ImageFont.truetype(font_path, mid)
        h = measure_digit_height(f)
        if h <= target_h:
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1
    return best


def rasterize(font, chars):
    ascent, descent = font.getmetrics()
    line_h = ascent + descent

    # First pass: rasterize each char onto a private canvas with consistent
    # origin. "Top of line" = y=0. Baseline = y=ascent.
    glyphs = {}
    canvas_w = font.size * 3
    canvas_h = line_h + font.size
    for ch in chars:
        img = Image.new("L", (canvas_w, canvas_h), 0)
        d = ImageDraw.Draw(img)
        d.text((font.size, 0), ch, font=font, fill=255)
        bbox = img.getbbox()
        advance = int(round(font.getlength(ch)))
        if bbox is None:
            glyphs[ch] = dict(w=0, h=0, advance=advance, ox=0, oy=0, bits=b"")
            continue
        l, t, r, b = bbox
        w, h = r - l, b - t
        crop = img.crop(bbox).point(lambda p: 255 if p >= 128 else 0, mode="1")
        stride = (w + 7) // 8
        data = bytearray(stride * h)
        px = crop.load()
        for y in range(h):
            for x in range(w):
                if px[x, y]:
                    data[y * stride + (x >> 3)] |= 0x80 >> (x & 7)
        glyphs[ch] = dict(
            w=w, h=h, advance=advance,
            ox=l - font.size,   # bearing from pen
            oy=t,                # from top-of-line
            bits=bytes(data),
        )
    return line_h, glyphs


def emit(fonts, header_path, source_path):
    # Header: just extern declarations.
    h = []
    h.append("#pragma once")
    h.append("")
    h.append('#include "BitmapFont.h"')
    h.append("")
    h.append(f"// Generated from {FONT_FILE} (keshikan, SIL OFL 1.1).")
    h.append(f"// Generated by tools/fontgen/gen.py. Defined in Fonts_{FONT_NAME}.cpp.")
    h.append("")
    for name, digit_h, _, _ in fonts:
        h.append(f"// digit height ~{digit_h}px")
        h.append(f"extern const BitmapFont {name};")
    h.append("")
    header_path.write_text("\n".join(h))

    # Source: bitmap arrays + glyph tables + font structs.
    s = []
    s.append(f'#include "Fonts_{FONT_NAME}.h"')
    s.append("")
    s.append(f"// Generated from {FONT_FILE} (keshikan, SIL OFL 1.1).")
    s.append("// Source: github.com/keshikan/DSEG  (fonts-DSEG_v046)")
    s.append(f"// Chars: {CHARS!r}")
    s.append("")

    for name, digit_h, line_h, glyphs in fonts:
        first = min(ord(c) for c in glyphs)
        last = max(ord(c) for c in glyphs)
        total_bytes = sum(len(g["bits"]) for g in glyphs.values())
        s.append(f"// === {name}  digit_h={digit_h}px line_h={line_h}px  "
                 f"bitmaps={total_bytes}B ===")
        s.append(f"namespace ns_{name} {{")
        s.append("")

        for ch in sorted(glyphs, key=ord):
            g = glyphs[ch]
            if g["w"] == 0:
                continue
            sym = f"bm_{ord(ch):02X}"
            stride = (g["w"] + 7) // 8
            s.append(f"// '{ch}'  {g['w']}x{g['h']}  adv={g['advance']}")
            s.append(f"constexpr uint8_t {sym}[] = {{")
            for y in range(g["h"]):
                row = g["bits"][y * stride:(y + 1) * stride]
                s.append("    " + ", ".join(f"0x{b:02X}" for b in row) + ",")
            s.append("};")
            s.append("")

        s.append(f"constexpr BitmapGlyph glyphs[] = {{")
        for code in range(first, last + 1):
            ch = chr(code)
            if ch in glyphs and glyphs[ch]["w"] > 0:
                g = glyphs[ch]
                sym = f"bm_{code:02X}"
                s.append(
                    f"    {{ {g['w']:3d}, {g['h']:3d}, {g['advance']:3d}, "
                    f"{g['ox']:3d}, {g['oy']:3d}, {sym} }},  // '{ch}'"
                )
            else:
                adv = glyphs.get(ch, {"advance": 0})["advance"]
                s.append(
                    f"    {{   0,   0, {adv:3d},   0,   0, nullptr }},  "
                    f"// code {code}"
                )
        s.append("};")
        s.append("")
        s.append(f"}} // namespace ns_{name}")
        s.append("")
        s.append(f"const BitmapFont {name} = {{")
        s.append(f"    {line_h}, {first}, {last}, ns_{name}::glyphs")
        s.append("};")
        s.append("")

    source_path.write_text("\n".join(s))


def main():
    fonts = []
    for target in TARGETS:
        size = pick_size_for_digit_height(FONT_FILE, target)
        font = ImageFont.truetype(FONT_FILE, size)
        actual = measure_digit_height(font)
        line_h, glyphs = rasterize(font, CHARS)
        name = f"{FONT_NAME}_{target}"
        bitmap_bytes = sum(len(g["bits"]) for g in glyphs.values())
        print(f"{name}: point_size={size}  digit_h={actual}px  "
              f"line_h={line_h}px  bitmaps={bitmap_bytes}B")
        fonts.append((name, target, line_h, glyphs))
    emit(fonts, OUT_HEADER, OUT_SOURCE)
    print(f"Wrote {OUT_HEADER}")
    print(f"Wrote {OUT_SOURCE}")


if __name__ == "__main__":
    main()
