#pragma once

#include "BitmapFont.h"

// Generated from DSEG14Classic-Bold.ttf (keshikan, SIL OFL 1.1).
// Generated by tools/fontgen/gen.py. Defined in Fonts_DSEG14.cpp.

// digit height ~96px
extern const BitmapFont DSEG14_96;
// digit height ~48px
extern const BitmapFont DSEG14_48;
