#pragma once

#include "BitmapFont.h"

// Generated by tools/fontgen/gen.py.

extern const BitmapFont DSEG7C_120;  // DSEG7Classic-Bold.ttf
extern const BitmapFont DSEG7M_120;  // DSEG7Modern-Bold.ttf
extern const BitmapFont ORBITRON_120;  // Orbitron[wght].ttf
extern const BitmapFont TEKO_120;  // Teko[wght].ttf
