#pragma once

#include "BitmapFont.h"

// Generated by tools/fontgen/gen.py.

extern const BitmapFont DSEG7_120;  // DSEG7Classic-Bold.ttf
extern const BitmapFont DSEG7_72;  // DSEG7Classic-Bold.ttf
extern const BitmapFont DSEG7_48;  // DSEG7Classic-Bold.ttf
