#pragma once

#include "BitmapFont.h"

// Generated by tools/fontgen/gen.py.

extern const BitmapFont DSEG7C_120;  // DSEG7Classic-Bold.ttf
extern const BitmapFont DSEG7C_72;  // DSEG7Classic-Bold.ttf
extern const BitmapFont DSEG7C_48;  // DSEG7Classic-Bold.ttf
extern const BitmapFont TEKO_120;  // Teko[wght].ttf
extern const BitmapFont TEKO_72;  // Teko[wght].ttf
extern const BitmapFont TEKO_48;  // Teko[wght].ttf
