#pragma once

#include "BitmapFont.h"

// Generated from DSEG7Classic-Bold.ttf (keshikan, SIL OFL 1.1).
// Generated by tools/fontgen/gen.py. Defined in Fonts_DSEG7.cpp.

// digit height ~120px
extern const BitmapFont DSEG7_120;
// digit height ~60px
extern const BitmapFont DSEG7_60;
