#pragma once

#include "BitmapFont.h"

// DSEG7 Classic Bold (keshikan, SIL OFL 1.1) — digits + colon/dot/dash/slash.
// Generated by tools/fontgen/gen.py. Defined in Fonts_DSEG7.cpp.

// digit height ~96px
extern const BitmapFont DSEG7_96;
// digit height ~48px
extern const BitmapFont DSEG7_48;
